version: '3.9'

services:
  agregator1:
    image: mysql:8.0
    container_name: mysql_agregator1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator1-db
    volumes:
      - ./mysql-agregator1:/docker-entrypoint-initdb.d
      - mysql-ag1-data:/var/lib/mysql
    ports:
      - "3311:3306"

  agregator2:
    image: mysql:8.0
    container_name: mysql_agregator2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator2-db
    volumes:
      - ./mysql-agregator2:/docker-entrypoint-initdb.d
      - mysql-ag2-data:/var/lib/mysql
    ports:
      - "3312:3306"

  agregator3:
    image: mysql:8.0
    container_name: mysql_agregator3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator3-db
    volumes:
      - ./mysql-agregator3:/docker-entrypoint-initdb.d
      - mysql-ag3-data:/var/lib/mysql
    ports:
      - "3313:3306"

  server:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server-db
    volumes:
      - ./mysql-server:/docker-entrypoint-initdb.d
      - mysql-server-data:/var/lib/mysql
    ports:
      - "3314:3306"

volumes:
  mysql-ag1-data:
  mysql-ag2-data:
  mysql-ag3-data:
  mysql-server-data:
