version: '3.9'

services:
  mysql1:
    image: mysql:8.0
    container_name: mysql_wavy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wavy-db
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql1:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  mysql2:
    image: mysql:8.0
    container_name: mysql_agregator
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator-db
    volumes:
      - ./mysql2:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

  mysql3:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server-db
    volumes:
      - ./mysql3:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
